core/urls.py
from django.urls import path
from core import views

urlpatterns = [
    path('', views.painel, name='painel'),
    path('participantes/', views.ver_participantes, name='ver_participantes'),
    path('pendentes/', views.participantes_pendentes, name='participantes_pendentes'),
    path('novo-participante/', views.criar_participante, name='criar_participante'),
    path('detalhes/<int:id_participante>/', views.detalhe_participante, name='detalhes_participante'),
    path('editar-participante/<int:id_participante>/', views.editar_participante, name='editar_participante'),
    path('excluir-participante<int:id_participante>', views.excluir_participante, name='excluir_participante'),
    path('questionario/<int:id_participante>/', views.aplicar_questionario, name='aplicar_questionario'),
    path('ver-questionario/<int:id_participante>/', views.ver_questionario, name='ver_questionario'),
    path('editar_questionario<int:id_questionario>/', views.editar_questionario, name='editar_questionario'),
    path('excluir-questionario<int:id_questionario>', views.excluir_questionario, name='excluir_questionario'),
]

deproject/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views as core_views
from core import urls as core_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('painel/', include(core_urls)),
    path('', core_views.index, name='index'),
]

core/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User
from datetime import date

GENERO_CHOICES = (('M', 'Masculino'), ('F', 'Feminino'))

QUALIDADE_SONO_CHOICES = [
    (1, 'Muito Baixa (Noites muito ruins, sono insatisfatório)'),
    (2, 'Baixa (Acordo frequentemente cansado)'),
    (3, 'Média (Tenho um sono razoável, mas poderia ser melhor)'),
    (4, 'Alta (Durmo bem na maioria das noites)'),
    (5, 'Muito Alta (Sono excelente, acordo revigorado)'),
]

NIVEL_ESTRESSE_CHOICES = [
    (1, 'Muito Baixo (Me sinto completamente relaxado)'),
    (2, 'Baixo (Me sinto tranquilo na maior parte do tempo)'),
    (3, 'Médio (Algum estresse, mas controlável)'),
    (4, 'Alto (Me sinto frequentemente sobrecarregado)'),
    (5, 'Muito Alto (Estresse constante, difícil de lidar)'),
]

PRESSAO_ARTERIAL_CHOICES = [
    ('Normal', 'Normal'),
    ('Elevated', 'Elevada'),
    ('Hypertension Stage 1', 'Hipertensão estágio 1'),
    ('Hypertension Stage 2', 'Hipertensão estágio 2'),
    ('Hypertensive Crisis', 'Crise hipertensiva')
]

PHONE_VALIDATOR = [RegexValidator(regex=r'^\d{10,11}$', message='Telefone inválido')]


class Pesquisador(models.Model):
    id_pesquisador = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Usuário')
    nome = models.CharField(max_length=100, verbose_name='Nome')
    genero = models.CharField(choices=GENERO_CHOICES, max_length=1, verbose_name='Gênero')
    dt_nascimento = models.DateField(verbose_name='Data de nascimento')
    cpf = models.CharField(
        max_length=11,
        validators=[RegexValidator(regex=r'^\d{11}$', message='CPF inválido')],
        unique=True,
        verbose_name='CPF'
    )
    email = models.EmailField(unique=True, verbose_name='Email')
    telefone = models.CharField(
        max_length=11,
        validators=PHONE_VALIDATOR,
        unique=True,
        verbose_name='Telefone'
    )
    instituicao = models.CharField(max_length=100, verbose_name='Instituição')
    dt_cadastro = models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')

    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'pesquisador'
        verbose_name = 'Pesquisador'
        verbose_name_plural = 'Pesquisadores'
        ordering = ['nome']


class Participante(models.Model):
    id_participante = models.AutoField(primary_key=True)
    id_pesquisador = models.ForeignKey(Pesquisador, on_delete=models.CASCADE, verbose_name='Pesquisador')
    nome = models.CharField(max_length=100, verbose_name='Nome')
    genero = models.CharField(choices=GENERO_CHOICES, max_length=1, verbose_name='Gênero')
    dt_nascimento = models.DateField(verbose_name='Data de nascimento')
    email = models.EmailField(verbose_name='Email', unique=True)
    telefone = models.CharField(
        max_length=11,
        validators=PHONE_VALIDATOR,
        unique=True,
        verbose_name='Telefone'
    )
    endereco = models.CharField(max_length=256, verbose_name='Endereço')
    dt_cadastro = models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')
    status_questionario = models.BooleanField(default=False, verbose_name='Status de questionario')

    def idade(self):
        hoje = date.today()
        idade = hoje.year - self.dt_nascimento.year - (
                (hoje.month, hoje.day) < (self.dt_nascimento.month, self.dt_nascimento.day))
        return idade

    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'participante'
        verbose_name = 'Participante'
        verbose_name_plural = 'Participantes'
        ordering = ['nome']


class Questionario(models.Model):
    id_questionario = models.AutoField(primary_key=True)
    id_pesquisador = models.ForeignKey(Pesquisador, on_delete=models.CASCADE)
    id_participante = models.ForeignKey(Participante, on_delete=models.CASCADE)
    dt_envio = models.DateTimeField(auto_now_add=True, verbose_name='Data de envio')
    duracao_sono = models.FloatField(verbose_name='Duração do sono')
    qualidade_sono = models.IntegerField(choices=QUALIDADE_SONO_CHOICES, verbose_name='Qualidade do sono')
    nivel_estresse = models.IntegerField(choices=NIVEL_ESTRESSE_CHOICES, verbose_name='Nível de estresse')
    pressao_arterial = models.CharField(choices=PRESSAO_ARTERIAL_CHOICES, verbose_name='Pressão sanguínea')
    frequencia_cardiaca = models.IntegerField(verbose_name='Frequência de cardíaca')
    atividade_fisica = models.IntegerField(verbose_name='Atividade Física')
    consumo_cafeina = models.BooleanField(verbose_name='Consome cafeína')
    consumo_alcool = models.BooleanField(verbose_name='Consome álcool')
    tabagismo = models.BooleanField(verbose_name='Fumante')
    problema_medico = models.BooleanField(verbose_name='Probelma médico')
    tomando_medicacao = models.BooleanField(verbose_name='Tomando medicação')
    uso_smartphone = models.BooleanField(verbose_name='Usa smartphone')
    tempo_medio_tela = models.FloatField(verbose_name='Tempo médio de tela')
    filtro_luz_azul = models.BooleanField(verbose_name='Filtro de luz azul')
    fadiga_ocular = models.BooleanField(verbose_name='Fadiga ocular')
    vermelhidao_ocular = models.BooleanField(verbose_name='Vermelhidão ocular')
    irritacao_ocular = models.BooleanField(verbose_name='Irritação ocular')
    chance_doenca = models.FloatField(verbose_name='Chance de docença')

    def __str__(self):
        return f'Questionário {self.id_questionario} - Pesquisador: {self.id_pesquisador.nome}'

    class Meta:
        db_table = 'questionario'
        verbose_name = 'Questionário'
        verbose_name_plural = 'Questionários'
        ordering = ['id_questionario']


class ParticipantesPendentes(models.Model):
    id_participante = models.IntegerField(primary_key=True)
    id_pesquisador_id = models.IntegerField()
    nome = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'participantes_pendentes'
        verbose_name = 'Participante pendente'
        verbose_name_plural = 'Participantes pendentes'

templates/painel/detalhe_participante.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Detalhes do participante</h1>

    <p><strong>Nome:</strong> {{ participante.nome }}</p>
    <p><strong>Gênero:</strong> {{ participante.get_genero_display }}</p>
    <p><strong>Data de Nascimento:</strong> {{ participante.dt_nascimento }}</p>
    <p><strong>Email:</strong> {{ participante.email }}</p>
    <p><strong>Telefone:</strong> {{ participante.telefone }}</p>
    <p><strong>Endereço:</strong> {{ participante.endereco }}</p>
    <p><strong>Data de Cadastro:</strong> {{ participante.dt_cadastro }}</p>
    <p>
        <strong>Situação do Questionário: {% if participante.status_questionario %}Enviado{% else %}
            Pendente{% endif %}</strong>
    </p>


    <a href="{% url 'editar_participante' participante.id_participante %}">Editar dados</a>

    <a href="{% url 'excluir_participante' participante.id_participante %}">Excluir participante</a>

    {% if participante.status_questionario %}
        <a href="{% url 'ver_questionario' participante.id_participante %}">Ver questionário</a>

    {% else %}
        <a href="{% url 'aplicar_questionario' participante.id_participante %}">Aplicar questionário</a>

    {% endif %}

{% endblock %}

templates/painel/lista_participantes.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Participantes</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Nome</th>
            <th>Status</th>
            <th>Ação</th>
        </tr>
        </thead>
        <tbody>
        {% for participante in participantes %}
            <tr>
                <td>{{ participante.nome }}</td>
                <td>
                    {% if participante.status_questionario %}Enviado{% else %}Pendente{% endif %}
                </td>
                <td><a href="{% url 'detalhes_participante' participante.id_participante %}">Ver detalhes</a></td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/painel/painel.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Painel</h1>
    <ul>
        <li><a href="{% url 'criar_participante' %}">Cadastrar Participante</a></li>
        <li><a href="{% url 'ver_participantes' %}">Ver participantes</a></li>
    </ul>
{% endblock %}

templates/painel/participantes_pendentes.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Participantes pendentes</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Nome</th>
            <th>Ação</th>
        </tr>
        </thead>
        <tbody>
        {% for participante in participantes %}
            <tr>
                <td>{{ participante.nome }}</td>
                <td><a href="{% url 'detalhes_participante' participante.id_participante %}">Ver detalhes</a></td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/painel/questionario.html
{% extends 'base/base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Salvar">
    </form>
{% endblock %}

templates/painel/registro_participante.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Novo participante</h1>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Salvar">
    </form>
{% endblock %}

templates/painel/ver_questionario.html
{% extends 'base/base.html' %}

{% load custom_filters %}

{% block content %}
    <h1>Detalhes do questionário</h1>

    <table>
        <thead>
        <tr>
            <th>Atributo</th>
            <th>Valor</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>Duração do sono</td>
            <td>{{ questionario.duracao_sono }}</td>
        </tr>
        <tr>
            <td>Qualidade do sono</td>
            <td>{{ questionario.qualidade_sono }}</td>
        </tr>
        <tr>
            <td>Nível de estresse</td>
            <td>{{ questionario.nivel_estresse }}</td>
        </tr>
        <tr>
            <td>Pressão sanguínea</td>
            <td>
                {% if questionario.pressao_arterial == 'Elevated' %}
                    Elevada
                {% elif questionario.pressao_arterial == 'Hypertension Stage 1' %}
                    Hipertensão estágio 1
                {% elif questionario.pressao_arterial == 'Hypertension Stage 2' %}
                    Hipertensão estágio 1
                {% elif questionario.pressao_arterial == 'Hypertensive Crisis' %}
                    Crise hipertensiva
                {% endif %}
            </td>
        </tr>
        <tr>
            <td>Frequência cardíaca</td>
            <td>{{ questionario.frequencia_cardiaca }}</td>
        </tr>
        <tr>
            <td>Atividade Física</td>
            <td>{{ questionario.atividade_fisica }}</td>
        </tr>
        <tr>
            <td>Distúrbio do sono</td>
            <td>{% if questionario.disturbio_sono %}Sim{% else %}Não{% endif %}</td>
        </tr>
        <tr>
            <td>Consome cafeína</td>
            <td>{% if questionario.consumo_cafeina %}Sim{% else %}Não{% endif %}</td>
        </tr>
        <tr>
            <td>Consome álcool</td>
            <td>{% if questionario.consumo_alcool %}Sim{% else %}Não{% endif %}</td>
        </tr>
        <tr>
            <td>Fumante</td>
            <td>{% if questionario.tabagismo %}Sim{% else %}Não{% endif %}</td>
        </tr>
        <tr>
            <td>Problema médico</td>
            <td>{% if questionario.problema_medico %}Sim{% else %}Não{% endif %}</td>
        </tr>
        <tr>
            <td>Tomando medicação</td>
            <td>{% if questionario.tomando_medicacao %}Sim{% else %}Não{% endif %}</td>
        </tr>
        <tr>
            <td>Usa smartphone</td>
            <td>{% if questionario.uso_smartphone %}Sim{% else %}Não{% endif %}</td>
        </tr>
        <tr>
            <td>Tempo médio de tela</td>
            <td>{{ questionario.tempo_medio_tela }}</td>
        </tr>
        <tr>
            <td>Filtro de luz azul</td>
            <td>{% if questionario.filtro_luz_azul %}Sim{% else %}Não{% endif %}</td>
        </tr>
        <tr>
            <td>Fadiga ocular</td>
            <td>{% if questionario.fadiga_ocular %}Sim{% else %}Não{% endif %}</td>
        </tr>
        <tr>
            <td>Vermelhidão ocular</td>
            <td>{% if questionario.vermelhidao_ocular %}Sim{% else %}Não{% endif %}</td>
        </tr>
        <tr>
            <td>Irritação ocular</td>
            <td>{% if questionario.irritacao_ocular %}Sim{% else %}Não{% endif %}</td>
        </tr>
        <tr>
            <td>Olho seco</td>
            <td>{{ questionario.chance_doenca|mul:100|floatformat:2 }}% de chance</td>
        </tr>
        </tbody>
    </table>

    <a href="{% url 'editar_questionario' questionario.id_questionario %}">Editar questionário</a>
    <a href="{% url 'excluir_questionario' questionario.id_questionario %}">Excluir questionário</a>
{% endblock %}